services:
  - type: web
    name: asset-tracking-system
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn webapp.wsgi:application
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - database: asset-tracking-db
        envVarKey: DATABASE_URL

databases:
  - name: asset-tracking-db
    plan: free
    ipAllowList: []
