# Generated by Django 6.0 on 2025-12-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESPStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_connected', models.BooleanField(default=False)),
                ('ap_ip', models.CharField(default='', max_length=20)),
                ('sta_ip', models.CharField(default='', max_length=20)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ESP Status',
                'verbose_name_plural': 'ESP Status',
            },
        ),
    ]
