# Generated by Django 6.0 on 2025-12-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_deviceownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='owner_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.DeleteModel(
            name='DeviceOwnership',
        ),
    ]
