# Generated by Django 6.0 on 2025-12-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_devicelog_created_date_devicelog_owner_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=120)),
                ('user_contact', models.CharField(blank=True, max_length=120)),
                ('user_department', models.CharField(blank=True, max_length=120)),
                ('checkout_time', models.DateTimeField(auto_now_add=True)),
                ('checkin_time', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Device Checkout',
                'verbose_name_plural': 'Device Checkouts',
            },
        ),
    ]
