# Generated by Django 6.0 on 2026-03-04 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_devicecheckout_approval_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicecheckout',
            name='device_id',
        ),
        migrations.AddField(
            model_name='devicecheckout',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='RegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=120, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('device_model', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registered Device',
                'verbose_name_plural': 'Registered Devices',
            },
        ),
        migrations.AddField(
            model_name='devicecheckout',
            name='registered_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='monitor.registereddevice'),
        ),
    ]
